version: '3.5'
name: hello-world-cluster
services:
  hello-world:
    image: hello-world:0.0.1-SNAPSHOT
    container_name: hello-world
    environment:
      - JAVA_OPTS=-Xmx80m -XX:MaxDirectMemorySize=32m -XX:MaxMetaspaceSize=64m -XX:ReservedCodeCacheSize=80m
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "8089:8080"
    expose:
      - 8080
    networks: [gemfire-cluster_gemfire-cluster-networks]
networks:
  gemfire-cluster_gemfire-cluster-networks:
    external: true
